### ISSUE TITLE
Condition|endswith is not matching case insensitive

### ISSUE THREAD

**Issue by veramine** [bradleyjkemp/sigma-go#23]
I am running into an issue where matching is not done case insensitive.  Here's the rule: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_susp_non_exe_image.yml

Here's the specific matching clause that is not working properly:
```
detection:
    known_image_extension:
        Image|endswith:
            - '.exe'
            - '.tmp' # sadly many installers use this extension
           
...
    condition: not known_image_extension and not 1 of filter*
```

Here's the input:

```
Image: "C:\\Windows\\System32\\SppExtComObj.Exe"
```

I would expect that to MATCH known_image_extension and therefore not match the condition.

However, it does NOT match known_image_extension as you can see here:

```
map[string]interface {}{"Image":"C:\\Windows\\System32\\SppExtComObj.Exe"}
event2 Match result {Match:true SearchResults:map[filter_com:false filter_emc_networker:false filter_empty:false filter_image:false filter_libreoffice:false filter_lzma_exe:false filter_msi_rollbackfiles:false filter_myq_server:false filter_null:false filter_nvidia:false filter_pstarts:false filter_screensaver:false filter_starts:false filter_visualstudio:false filter_vscode:false filter_winpakpro:false filter_winscp:false filter_wsl:false known_image_extension:false] ConditionResults:[true]}
```

However, if I change the rule to match the case it works properly:

```
detection:
    known_image_extension:
        Image|endswith:
            - '.Exe'
            - '.exe'
            - '.tmp' # sadly many installers use this extension
```

Then the same input matches known_image_extension and therefore does not match the condition:

```
map[string]interface {}{"Image":"C:\\Windows\\System32\\SppExtComObj.Exe"}
event2 Match result {Match:false SearchResults:map[filter_com:false filter_emc_networker:false filter_empty:false filter_image:false filter_libreoffice:false filter_lzma_exe:false filter_msi_rollbackfiles:false filter_myq_server:false filter_null:false filter_nvidia:false filter_pstarts:false filter_screensaver:false filter_starts:false filter_visualstudio:false filter_vscode:false filter_winpakpro:false filter_winscp:false filter_wsl:false known_image_extension:true] ConditionResults:[false]}
```

**Comment by bradleyjkemp** [comment]
Ah that's an interesting discovery. On checking [the specification](https://github.com/SigmaHQ/sigma-specification/blob/aeab5a39ac6291547536aeb11c229460471dfda1/Sigma_1_0_2.md#general) it does seem that **all** values are supposed to be treated as case insensitive (which isn't something `sigma-go` does at all at the moment)

Definitely needs to be fixed but I'll need to have a think about how this plays with the other stipulation that
> Regular expressions are case-sensitive by default
