### ISSUE TITLE
[IDEA] Type-Aware Rule Parsing

### ISSUE THREAD

**Issue by calebstewart** [bradleyjkemp/sigma-go#30]
I'm curious on your thoughts here. I am using this repo, but mainly just for the rule parsing. I have separate evaluation logic for our use internally. This logic would be improved with the ability to retain the type information from Sigma searches in YAML format. Currently, all values (i.e. float, string, integer) are loaded as strings. If  the value is not scalar, it is empty when loaded by `sigma-go`.

I have tested this with the following modifications to the Field Matcher struct:

```go
type FieldMatcher struct {
	Field     string
	Modifiers []string
	Values    []interface{}
}

func (f *FieldMatcher) unmarshal(field *yaml.Node, values *yaml.Node) error {
	fieldParts := strings.Split(field.Value, "|")
	f.Field, f.Modifiers = fieldParts[0], fieldParts[1:]

	switch values.Kind {
	case yaml.ScalarNode:
		f.Values = []interface{}{nil}
		return values.Decode(&f.Values[0])
	case yaml.SequenceNode:
		return values.Decode(&f.Values)
	case yaml.MappingNode:
		fallthrough
	case yaml.DocumentNode:
		f.Values = []interface{}{map[string]interface{}{}}
		return values.Decode(&f.Values[0])
	case yaml.AliasNode:
		return f.unmarshal(field, values.Alias)
	}
	return nil
}
```
This works as long as you don't import `evaluator`, but breaks the evaluator implementation currently. Since I don't use the evaluator that is bundled here, I wanted to check if this was something you'd be interested in supporting before going any further down this road. To be clear, I'd be okay with making the necessary modifications to the evaluator to support/understand the `interface{}` value types myself, and submit a full PR. I just don't want to go down that path if it's not something you agree with as the project owner.

My use-case is basically that there are some things like `|gt` or `|lt` modifiers which operate on numeric values or more complex custom Sigma additions which require structured/typed data in the field matcher values. For example, internally we have a `|nested` modifier which interprets the value as a separate condition operating on nested documents within the event. This is impossible to implement since the current parser drops any values that aren't scalar.

If you're not interested here, I may end up maintaining an internal fork, but I'd love to push whatever I can back upstream if you're interested. :smiley:

**Comment by calebstewart** [comment]
For reference, the branch I am currently working under in my fork is [feature/type-aware-field-matcher](https://github.com/calebstewart/sigma-go/tree/feature/type-aware-field-matcher) although it's based on #29 because you had already approved that PR, so I was expected a merge relatively soon and wanted to test all these changes together with some of our internal stuff.

I did go through the evaluator a bit to see if I could get it working since I realized most of the logic was contained in one function, so the changes weren't too drastic. The tests still pass in that branch, so that's promising, but I'm still happy to discuss this further. I'm just tinkering for now. :P

**Comment by bradleyjkemp** [comment]
Yeah this is definitely something I've been thinking about: the `gt` and `lt` modifiers would be useful to get working.

Until now I'd been considering a JavaScript-style type coercion approach i.e. keep everything as strings but when using the `gt`/`lt` modifier it would try to parse both values as a number before comparing them (which is currently [how the `cidr` modifier works](https://github.com/bradleyjkemp/sigma-go/blob/bcfe96c5f0cbb2092f57b94c32d8f97feebf4c70/evaluator/modifiers.go#L60-L71))

Ultimately _some_ amount of type coercion is going to be necessary (YAML makes it ambiguous whether `1` is a number of an unquoted string) but having types wouldn't hurt here.

I think this approach is good 👍🏻 `Values []interface{}` means any type information from the rule can be used by the evaluator for better comparisons and it happens to let your `nested` modifier work too

It's not ideal that this pushes some rule validation cases [to evaluation time](https://github.com/calebstewart/sigma-go/compare/feature/marshal-rules...calebstewart:sigma-go:feature/type-aware-field-matcher#diff-e9cf3d259e762dc6ca77d37a5947e3fc45ac4c6976accd73fd4a5bac98076085R147-R161), but that's already the case in a few places (and can be caught by `sigmafmt`)
